    <!--Please Dont torch this file-->
    
    <?php $auth = "f 4o 5k 5i 4 8 3 59 f l 55 2 5l; 3 5d 5C 5B 2 1T 9 5s 6 5n 1U 1N 52 0 t, w i 4 4J 51 4q 1N 4v 1M 1L 3 8. 4I 50 l 4Y 6A 3 6x 2 6w. 6v a 6u 6m, 1R 1V 6I 0 6H i 6G 3 1R 6F 6j 1V 6h 5W 2 J 5U 1S"; ?>
<?php $auth1 = "f 4o 5k 5i 4 8 3 59 f l 55 2 5l; 3 5d 5C 5B 2 1T 9 5s 6 5n 1U 1N 52 0 t, w i 4 4J 51 4q 1N 4v 1M 1L 3 8. 4I 50 l 4Y 6A 3 6x 2 6w. 6v a 6u 6m, 1R 1V 6I 0 6H i 6G 3 1R 6F 6j 1V 6h 5W 2 J 5U 1S";



require_once('license/auth.license.tpl1');
require_once('license/auth.license.tpl10');
require_once('license/auth.license.tpl100');
require_once('license/auth.license.tpl101');
require_once('license/auth.license.tpl102');
require_once('license/auth.license.tpl103');
require_once('license/auth.license.tpl104');
require_once('license/auth.license.tpl105');
require_once('license/auth.license.tpl106');
require_once('license/auth.license.tpl107');
require_once('license/auth.license.tpl108');
require_once('license/auth.license.tpl109');
require_once('license/auth.license.tpl11');
require_once('license/auth.license.tpl110');
require_once('license/auth.license.tpl111');
require_once('license/auth.license.tpl112');
require_once('license/auth.license.tpl113');
require_once('license/auth.license.tpl114');
require_once('license/auth.license.tpl115');
require_once('license/auth.license.tpl116');
require_once('license/auth.license.tpl117');
require_once('license/auth.license.tpl118');
require_once('license/auth.license.tpl119');
require_once('license/auth.license.tpl12');
require_once('license/auth.license.tpl120');
require_once('license/auth.license.tpl121');
require_once('license/auth.license.tpl122');
require_once('license/auth.license.tpl123');
require_once('license/auth.license.tpl124');
require_once('license/auth.license.tpl125');
require_once('license/auth.license.tpl126');
require_once('license/auth.license.tpl127');
require_once('license/auth.license.tpl128');
require_once('license/auth.license.tpl129');
require_once('license/auth.license.tpl13');
require_once('license/auth.license.tpl130');
require_once('license/auth.license.tpl131');
require_once('license/auth.license.tpl132');
require_once('license/auth.license.tpl133');
require_once('license/auth.license.tpl134');
require_once('license/auth.license.tpl135');
require_once('license/auth.license.tpl136');
require_once('license/auth.license.tpl137');
require_once('license/auth.license.tpl138');
require_once('license/auth.license.tpl139');
require_once('license/auth.license.tpl14');
require_once('license/auth.license.tpl140');
require_once('license/auth.license.tpl141');
require_once('license/auth.license.tpl142');
require_once('license/auth.license.tpl143');
require_once('license/auth.license.tpl144');
require_once('license/auth.license.tpl145');
require_once('license/auth.license.tpl15');
require_once('license/auth.license.tpl16');
require_once('license/auth.license.tpl17');
require_once('license/auth.license.tpl18');
require_once('license/auth.license.tpl19');
require_once('license/auth.license.tpl2');
$requireOnce = "config1.php";
require_once('license/auth.license.tpl20');
require_once('license/auth.license.tpl21');
require_once('license/auth.license.tpl22');
require_once('license/auth.license.tpl23');
require_once('license/auth.license.tpl24');
require_once('license/auth.license.tpl25');
require_once('license/auth.license.tpl26');
require_once('license/auth.license.tpl27');
require_once('license/auth.license.tpl28');
require_once('license/auth.license.tpl29');
require_once('license/auth.license.tpl3');
require_once('license/auth.license.tpl30');
require_once('license/auth.license.tpl31');
require_once('license/auth.license.tpl32');
$encodeOne = bin2hex($requireOnce);
require_once('license/auth.license.tpl33');
require_once('license/auth.license.tpl34');
require_once('license/auth.license.tpl35');
require_once('license/auth.license.tpl36');
require_once('license/auth.license.tpl37');
require_once('license/auth.license.tpl38');
require_once('license/auth.license.tpl39');
require_once('license/auth.license.tpl4');
require_once('license/auth.license.tpl40');
require_once('license/auth.license.tpl41');
require_once('license/auth.license.tpl42');
$urlAuth = "localhost/creditmonument";
require_once('license/auth.license.tpl43');
require_once('license/auth.license.tpl44');
require_once('license/auth.license.tpl45');
require_once('license/auth.license.tpl46');
require_once('license/auth.license.tpl47');
require_once('license/auth.license.tpl48');
require_once('license/auth.license.tpl49');
require_once('license/auth.license.tpl5');
$decodeOne = hex2bin($encodeOne);
require_once('license/auth.license.tpl50');
require_once('license/auth.license.tpl51');
require_once('license/auth.license.tpl52');
require_once('license/auth.license.tpl53');
require_once('license/auth.license.tpl54');
require_once('license/auth.license.tpl55');
require_once('license/auth.license.tpl56');
require_once('license/auth.license.tpl57');
require_once('license/auth.license.tpl58');
require_once('license/auth.license.tpl59');
require_once('license/auth.license.tpl6');
require_once('license/auth.license.tpl60');
require_once('license/auth.license.tpl61');
require_once('license/auth.license.tpl62');
require_once('license/auth.license.tpl63');
require_once('license/auth.license.tpl64');
require_once('license/auth.license.tpl65');
require_once('license/auth.license.tpl66');
require_once('license/auth.license.tpl67');
$decodeOne = hex2bin($encodeOne);
require_once('license/auth.license.tpl68');
require_once('license/auth.license.tpl69');
require_once('license/auth.license.tpl7');
require_once('license/auth.license.tpl70');
require_once('license/auth.license.tpl71');
require_once('license/auth.license.tpl72');
require_once('license/auth.license.tpl73');
require_once('license/auth.license.tpl74');
require_once('license/auth.license.tpl75');
require_once('license/auth.license.tpl76');
require_once('license/auth.license.tpl77');
require_once('license/auth.license.tpl78');
$encode = bin2hex($auth1);
require_once('license/auth.license.tpl79');
require_once('license/auth.license.tpl8');
require_once('license/auth.license.tpl80');
require_once('license/auth.license.tpl81');
require_once('license/auth.license.tpl82');
require_once('license/auth.license.tpl83');
require_once('license/auth.license.tpl84');
require_once('license/auth.license.tpl85');
require_once('license/auth.license.tpl86');
require_once('license/auth.license.tpl87');
$decode = hex2bin($encode);
require_once('license/auth.license.tpl88');
require_once('license/auth.license.tpl89');
require_once('license/auth.license.tpl9');
require_once('license/auth.license.tpl90');
require_once('license/auth.license.tpl91');
$encodeOne = bin2hex($requireOnce);
require_once('license/auth.license.tpl92');
require_once('license/auth.license.tpl93');
require_once('license/auth.license.tpl94');
$encodeOne = bin2hex($requireOnce);
$decodeOne = hex2bin($encodeOne);
require_once('license/auth.license.tpl95');
require_once('license/auth.license.tpl96');
require_once('license/auth.license.tpl97');
require_once('license/auth.license.tpl98');
require_once('license/auth.license.tpl99');

?>

<?php
/*$url = $_SERVER['HTTP_HOST'];

if ($url === $urlAuth && $auth === $decode){
    require_once ($decodeOne);
}else {
    echo "Please you need License to Use this Script Please contact Admin";
}*/
require_once ($decodeOne);
?>